# This notebook talke the raw output from Hamiltonian Replica Exchange, extract the dihedral angle from xtc file using MdTraj, and ananlyze the autocoorelation curve

In [1]:
import os, sys, glob, shutil, re
import subprocess

import mdtraj as md
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import pandas as pd
import math
from IPython.display import Image, display
%matplotlib inline
nmer = 5
mpl.rcParams.update({'font.size': 16})

In [2]:
%pwd

'/Users/starwingchen/Voelz_Lab/git/peptoid_ESM/REDs/analysis'

In [3]:
# Define the directory path
directory = "omega_data/"

# Check if the directory exists
if os.path.exists(directory):
    # Remove all contents of the directory
    shutil.rmtree(directory)
    # Recreate the empty directory
    os.makedirs(directory)
    print(f"All contents in '{directory}' have been cleared.")
else:
    # Create the directory if it does not exist
    os.makedirs(directory)
    print(f"Directory '{directory}' did not exist, so it has been created.")


All contents in 'omega_data/' have been cleared.


In [7]:
# hand input the omega indices:
# Define omega dihedral indices, gromcas start from 1, while np start from 0
gmx_dihedral_indices = np.array([
    [6, 7, 18, 36],
    [36, 39, 41, 45],
    [45, 46, 57, 75]

])

omega_dihedral_indices = gmx_dihedral_indices - 1
print(omega_dihedral_indices)

# Ensure the omega_data directory exists
omega_path = 'omega_data/'
omegas_list = []

trrfile = f"../traj/REDS.trr"
grofile = f"../single_peptoid.gro"

traj = md.load(trrfile, top=grofile)

omegas = md.compute_dihedrals(traj, omega_dihedral_indices) * (180.0 / math.pi)
omegas_list.append(omegas)

concatenated_omegas = np.vstack(omegas_list)
outfile = os.path.join(omega_path, f"omegas_state0.npy")
np.save(outfile, concatenated_omegas)
print(f"Saved omegasto {outfile}")


[[ 5  6 17 35]
 [35 38 40 44]
 [44 45 56 74]]
Saved omegasto omega_data/omegas_state0.npy


### What are the dimensions of the omega-angle arrays in each Hamiltonian state? 

In [8]:
print(np.load('omega_data/omegas_state0.npy')[:5])
print(np.load('omega_data/omegas_state0.npy').shape)

[[-147.41861  160.16226 -176.02151]
 [-158.49817  147.35365 -159.85147]
 [-173.71101 -162.60245 -163.55423]
 [-179.73349  168.35565 -159.64848]
 [ 166.53426  174.07317  178.95737]]
(2501, 3)
